replicaCount: 2

image:
  repository: saroja21/person-service
  tag: "master"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

database:
  name: persondb
  user: postgres
  password: postgres123

