spring:
  application:
    name: person-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
